name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Login to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Set registry for GitHub Packages
        run: echo "@OWNER:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Publish Package
        run: npm publish --access public
